<?php

/**
 * @file
 * A light-weight, customizable lightbox plugin for jQuery 1.3
 */

/**
 * The default path to the Colorbox directory.
 */
define('COLORBOX_MIN_PLUGIN_VERSION', '1.3.21.1');


/**
 * Implements hook_theme().
 */
function colorbox_theme() {
  return array(
    'colorbox_imagefield' => array(
      'variables' => array(
        'image' => array(),
        'path' => NULL,
        'title' => NULL,
        'gid' => NULL,
      ),
      'file' => 'colorbox.theme.inc',
    ),

    'colorbox_insert_image' => array(
      'variables' => array(
        'item' => NULL,
        'widget' => NULL,
      ),
      'template' => 'colorbox-insert-image',
      'file' => 'colorbox.theme.inc',
    ),

    'colorbox_image_formatter' => array(
      'variables' => array(
        'item' => NULL,
        'entity_type' => NULL,
        'entity' => NULL,
        'node' => NULL,  // Left for legacy support.
        'field' => array(),
        'path' => drupal_get_path('module', 'colorbox') . '/templates',
        'display_settings' => array(),
      ),
      'file' => 'colorbox.theme.inc',
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function colorbox_libraries_info() {
  $libraries['colorbox'] = array(
    'name' => 'Colorbox plugin',
    'vendor url' => 'http://www.jacklmoore.com/colorbox',
    'download url' => 'https://github.com/jackmoore/colorbox/archive/1.x.zip',
    'version arguments' => array(
      'file' => 'jquery.colorbox-min.js',
      'pattern' => '@(?i:Colorbox) v([0-9\.a-z]+)@',
      'lines' => 5,
    ),
    'files' => array(
      'js' => array(
        'jquery.colorbox-min.js',
      ),
    ),
    'variants' => array(
      'minified' => array(
        'files' => array(
          'js' => array(
            'jquery.colorbox-min.js',
          ),
        ),
      ),
      'source' => array(
        'files' => array(
          'js' => array(
            'jquery.colorbox.js',
          ),
        ),
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_menu().
 */
function colorbox_menu() {
  $items = array();

  $items['colorbox_settings'] = array(
    'title' => 'Colorbox',
    'description' => 'Adjust Colorbox settings.',
    'route_name' => 'colorbox_settings',
  );

  return $items;
}

/**
 * Check if Colorbox should be active for the current URL.
 *
 * @return
 *   TRUE if Colorbox should be active for the current page.
 */
function _colorbox_active() {
  // Make it possible deactivate Colorbox with
  // parameter ?colorbox=no in the url.
  if (isset($_GET['colorbox']) && $_GET['colorbox'] == 'no') {
    return FALSE;
  }

  $config = config('colorbox.settings');

  $current_path = current_path();
  // Code from the block_list funtion in block.module.

  $path = Drupal::service('path.alias_manager.cached')->getPathAlias($current_path);
  $colorbox_pages = $config->get('colorbox_pages');
  // Compare with the internal and path alias (if any).
  $page_match = drupal_match_path($path, $colorbox_pages);
  if ($path != $current_path) {
    $page_match = $page_match || drupal_match_path($current_path, $colorbox_pages);
  }
  $page_match = $config->get('advanced.visibility') == 0 ? !$page_match : $page_match;

  return $page_match;
}

/**
 * Implements hook_insert_styles().
 */
function colorbox_insert_styles() {
  $insert_styles = array();
  foreach (image_styles() as $key => $style) {
    $insert_styles['colorbox__' . $key] = array('label' => t('Colorbox @style', array('@style' => $style['name'])));
  }

  return $insert_styles;
}

/**
 * Implements hook_insert_content().
 */
function colorbox_insert_content($item, $style, $widget) {
  list($item['module_name'], $item['style_name']) = explode('__', $style['name'], 2);
  return theme('colorbox_insert_image', array('item' => $item, 'widget' => $widget));
}

/**
 * Machine names normally need to be unique but that does not apply to galleries.
 *
 * @return
 *   Always FALSE
 */
function colorbox_gallery_exists() {
  return FALSE;
}
